version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - SNOWFLAKE_DATABASE=LLM
      - SNOWFLAKE_SCHEMA=RAG
      - SNOWFLAKE_WAREHOUSE=COMPUTE_WH
      - SNOWFLAKE_ROLE=ACCOUNTADMIN
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
