name: getting_started_llmops
channels:
  - conda-forge
  - snowflake
dependencies:
  - python=3.11
  - pip
  - numpy
  - snowflake-snowpark-python
  - snowflake-ml-python
  - snowflake-connector-python=2.7.0
  - notebook
  - ipykernel
  - pip:
    - trulens-core
    - trulens-providers-cortex
    - trulens-connectors-snowflake
    - llama-index
    - llama-index-embeddings-huggingface
    - llama-index-readers-github
    - snowflake-sqlalchemy
    - fastapi==0.68.0
    - uvicorn==0.15.0
    - crawl4ai==1.0.0
    - websockets==10.0
    - aiohttp==3.8.0
    - python-dotenv==0.19.0
    - pydantic==1.8.2
    - python-multipart==0.0.5
    - email-validator==1.1.3
    - requests==2.26.0
    - httpx==0.23.0
    - asyncio==3.4.3
    - typing-extensions==4.0.1
    - cryptography==36.0.1
