# API configuration
api_url = "http://localhost:8000"  # For local development
ws_url = "ws://localhost:8000"

# Snowflake configuration
[snowflake]
account = "sluqyqs-xvb39431"
user = "SURYAMADHAV"
password = "Srinijani@95"
database = "LLM"
schema = "RAG"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
