# API Configuration
api_url = "http://localhost:8000"  # Backend API URL

[api]
discovery_timeout = 300  # customize if needed
crawl_timeout = 600     # customize if needed

[snowflake]
account = "sluqyqs-xvb39431"
user = "SURYAMADHAV"
warehouse = "MEDIUM"
database = "LLM"
schema = "RAG"

password = "Srinijani@95"  # Basic authentication
